### ISSUE TITLE
Ubuntu generic system kernel results in error.

### ISSUE THREAD

**Issue by quintenvandamme** [quintenvandamme/trident#2]
When trying to install or compile a kernel trident gives a error from the function **check_if_kernel_is_lower** (package:Trident/sys/checks.dart:26). 

## sys info
```bash
quiten@mainframe:~$ trident --version
  _   _   _
 / \ / \ / \      Version:     0.0.4-rc7
 | | | | | |      System:      Linux Ubuntu 21.10
 | | | | | |      Arch:        x86_64
 \ |_| |_| /      Kernel:      5.13.0-39-generic
  \__   __/
     | |
     | |
     | |
     \_/
```

## log:
```bash
quiten@mainframe:~$ trident -compile 5.18-rc1
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
5130-39-generic0
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:131)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:142)
#2      int._parse (dart:core-patch/integers_patch.dart:103)
#3      int.parse (dart:core-patch/integers_patch.dart:65)
#4      convert_kernel_toint (package:Trident/kernel/main.dart:11)
#5      kernel_version_is_lower (package:Trident/sys/checks.dart:26)
#6      main.check_if_kernel_is_lower (file:///mnt/c/Users/quinten.vandamme/dev/trident/bin/cli.dart:25)
#7      main.check_if_kernel_is_lower (file:///mnt/c/Users/quinten.vandamme/dev/trident/bin/cli.dart:24)
#8      main.commands (file:///mnt/c/Users/quinten.vandamme/dev/trident/bin/cli.dart:140)
<asynchronous suspension>
quiten@mainframe:~$ 
```

`

**Comment by quintenvandamme** [comment]
fixed in [1f9b9c1](https://github.com/quintenvandamme/trident/commit/1f9b9c1c1870d49b9bc57685379c4baa4c350a02)
